---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kbot
  namespace: demo-gitless
spec:
  chart:
    spec:
      chart: ./helm
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: kbot
  interval: 1m0s
  values:
    gateway:
      hostname: "gitless-kbot.k3s.comelove.pp.ua"
  postRenderers:
    - kustomize:
        images:
          - name: ghcr.io/vkamlov/kbot-src
            newTag: << inputs.image.tag | quote >>
