---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kbot
  namespace: demo-gitless
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/vkamlov/kbot-src
